name: Validate with hassfest

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  schedule:
    - cron:  '0 0 * * *'
    
jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Test hassfest
        uses: ./hassfest